config/routes.rb
Rails.application.routes.draw do
  root "home#top"
  get "users/show", to: "users#show"
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 
  

  get "/" , to: "home#top"
  resources :users, only: [:show] 
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user_id, presence: true
  validates :post_id, presence: true
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    like = current_user.likes.new(post_id: params[:post_id])
    like.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @post = Post.find(params[:post_id])
    like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
    like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if @post.liked_by?(current_user) %>
  <%= link_to(post_like_path(@post), method: :delete) do %>
    <span class="glyphicon glyphicon-heart" aria-hidden="true" style="font-size: 14px"></span>
  <% end %>
<% else %>
  <%= link_to(post_likes_path(@post), method: :post) do %>
    <span class="glyphicon glyphicon-heart-empty" aria-hidden="true" style="font-size: 14px"></span>
  <% end %>
<% end %>
<%= @likes_count %>