config/routes.rb
Rails.application.routes.draw do
  root "home#top"
  get "users/show", to: "users#show"
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 
  

  get "/" , to: "home#top"
  resources :users, only: [:show] 
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  #validates :content_or_picture, presence :true
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  has_many :likes
  has_many :users, through: :likes
  has_many :comments, dependent: :destroy
  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  def like(user)
    likes.create(user_id: user.id)
  end

  def unlike(user)
    likes.find_by(user_id: user.id).destroy
  end
  private

  def content_or_picture
    content.presence or picture.presence
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :correct_user, only: [:destroy]

    def index
      @posts = Post.all
      @post = Post.new
    end

    def show
      @post = Post.find_by(id: params[:id])
      @like = Like.new
      @likes_count = Like.where(post_id: @post.id).count
      @comment = Comment.new
      @comments = @post.comments
      @comments_count = Comment.where(post_id: @post.id).count
    end
    
    def new
      @post = Post.new
    end

    def create
      @post = current_user.posts.build(post_params)
      if @post.save
        flash[:notice] = "投稿完了！"
        redirect_to posts_path
      end
    end

    def edit
      @post = Post.find_by(id: params[:id])
    end

    def destroy
      @post = Post.find_by(id: params[:id])
      @post.destroy
      redirect_to posts_path
    end

    private

    def post_params
      params.require(:post).permit(:content, :title, :picture)
    end

    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      unless @post
        redirect_to root_path
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post_form.html.erb
<%= form_for(@post) do |f| %>
　<div class="field">
    <%= f.label "Title" %><br />
    <%= f.text_field :title, placeholder: "書いて！", class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label "Content" %><br />
    <%= f.text_area :content, placeholder: "つぶやけ！", class: 'form-control' %>
  </div>

  <span class="picture">
    <%= f.label "Picture" %>
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png', placeholder: "何見せる？", class: 'form-control' %>
  </span>
  <%= f.submit "Post", class: "btn btn-success btn-lg" %>
<% end %>

app/views/posts/edit.html.erb
<div class="post-new-container">
  <p>Post Editしましょう</p>
</div>

app/views/posts/index.html.erb
<div class="post_index-container">
  <ul>
    <% @posts.each do |post| %>
      <li>
        <%= link_to(post.content, post_path(post), class: 'text-info') %>
      </li>
    <% end %>
  </ul>
</div>

app/views/posts/new.html.erb
<div class="post-new-container">
  <div class="form-group">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="post_form">
          <%= render 'posts/post_form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="main posts-show">
  <div class="container">
    <div class="posts-show-item">
      <%= @post.content %>
      <%= image_tag @post.picture if @post.picture? %>
      <div class="post-time">
        <%= @post.created_at %>
        <br>
        <span class="timestamp"><%= time_ago_in_words(@post.created_at) %> ago</span>
      </div>
      <div class="pull-right">
        <%= link_to(edit_post_path) do %>
          <span class="glyphicon glyphicon-edit" aria-hidden="true" style="font-size: 14px"></span>
        <% end %>
        <% if current_user == @post.user %>
          <%= link_to(post_path, method: :delete) do %>
            <span class="glyphicon glyphicon-trash" aria-hidden="true" style="font-size: 14px"></span>
          <% end %>
        <% end %>
        <%= render "likes/like" %>
      </div>
    </div>
  </div>
</div>
<div class="comment-container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <span class="glyphicon glyphicon-comment"></span>
      <%= @comments_count %>
      <h3 class="panel-title">All Comments</h3>
    </div>
  </div>
  <% @comments.each do |comment| %>
    <ul>
      <li>
        <%= comment.user.email %>
        <br>
        <%= comment.content %>
        <br>
        <% if current_user == comment.user %>
          <%= link_to(post_comment_path(@post, comment), method: :delete) do %>
            <span class="glyphicon glyphicon-trash" aria-hidden="true" style="font-size: 14px"></span>
          <% end %>
        <% end %>
      </li>
    </ul>
  <% end %>
  <%= form_for [@post, @comment] do |f| %>
    <%= f.text_area :content, :size => "98x5", placeholder: 'コメントを書いてください' %>
    <br>
    <%= f.submit 'コメントする', class: 'btn btn-success' %>
    <% end %>
  <%= link_to "ホームへ戻る", posts_path %> 
</div>